console.log('UBA IMS - User Information Management System');
console.log('-------------------------------------------');
console.log('Available commands:');
console.log('- npm run user:create fname <Name> lname <Surname>');
console.log('- npm run user:read [id <UserID> | fname <Name> [lname <Surname>]]');
// console.log('- npm run user:update id <UserID> [fname <NewName>] [lname <NewSurname>]');
// console.log('- npm run user:delete fname <Name> [--all]');
// console.log('- npm run user:delete id <UserID>');
console.log('-------------------------------------------');
console.log('For more details, check the README.md');